Repository AlmostFullStack/TUTRD_Android, pull requests merged in 2024-08, with the labels that each got.

#9 📝 Docs: classroom screen, classroom card UI added
  app/src/main/java/com/afs/tutrd/component/colordot/ColorDot.kt
  app/src/main/java/com/afs/tutrd/component/tooltip/Tooltip.kt
  app/src/main/java/com/afs/tutrd/component/topbar/ClassroomTopBar.kt
  app/src/main/java/com/afs/tutrd/di/RepositoryModule.kt
  app/src/main/java/com/afs/tutrd/domain/HealthCheck.kt
  app/src/main/java/com/afs/tutrd/domain/healthCheck/HealthCheckRepository.kt
  app/src/main/java/com/afs/tutrd/navigation/classroom/ClassroomNavigation.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/ClassroomScreen.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomIntent.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomSideEffect.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomState.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/view/ClassroomCard.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/view/ClassroomScreen.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/viewmodel/ClassroomViewModel.kt
  app/src/main/java/com/afs/tutrd/presentation/home/view/calendar/EventDots.kt
  app/src/main/java/com/afs/tutrd/theme/Color.kt
  app/src/main/java/com/afs/tutrd/theme/Theme.kt
  app/src/main/res/drawable/ic_info.xml
Labels: documentation

#12 Feature/calendar
  app/src/main/java/com/afs/tutrd/presentation/home/contract/HomeIntent.kt
  app/src/main/java/com/afs/tutrd/presentation/home/contract/HomeState.kt
  app/src/main/java/com/afs/tutrd/presentation/home/stateholder/CalendarState.kt
  app/src/main/java/com/afs/tutrd/presentation/home/util/CalendarDisplayText.kt
  app/src/main/java/com/afs/tutrd/presentation/home/view/HomeScreen.kt
  app/src/main/java/com/afs/tutrd/presentation/home/view/calendar/Day.kt
  app/src/main/java/com/afs/tutrd/presentation/home/viewmodel/HomeViewModel.kt
Labels: bug

#14 Feature/firebase
  app/build.gradle.kts
  app/src/main/java/com/afs/tutrd/data/constant/firestore/Collection.kt
  app/src/main/java/com/afs/tutrd/data/constant/firestore/Field.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/ClassroomData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/HomeworkData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/HomeworkImageData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/ProgressImagesData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/RepetitionData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/TimetableData.kt
  app/src/main/java/com/afs/tutrd/data/model/classroom/TutoringData.kt
  app/src/main/java/com/afs/tutrd/data/repository/classroom/ClassroomRepositoryImpl.kt
  app/src/main/java/com/afs/tutrd/di/DispatcherModule.kt
  app/src/main/java/com/afs/tutrd/di/FirebaseModule.kt
  app/src/main/java/com/afs/tutrd/di/RepositoryModule.kt
  app/src/main/java/com/afs/tutrd/di/qualifier/CoroutinesQualifier.kt
  app/src/main/java/com/afs/tutrd/domain/repository/classroom/ClassroomRepository.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/ClassroomScreen.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/ClassroomViewModel.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomIntent.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomSideEffect.kt
  app/src/main/java/com/afs/tutrd/presentation/classroom/contract/ClassroomState.kt
  build.gradle.kts
Labels: feature
